CREATE TABLE produto_tag
(
    produto_id BIGINT NOT NULL,
    tag_id     BIGINT NOT NULL
);

CREATE TABLE tb_arquivo
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    content_type VARCHAR(255),
    size         BIGINT,
    url          VARCHAR(255),
    hash         VARCHAR(255),
    produto_id   BIGINT,
    CONSTRAINT pk_tb_arquivo PRIMARY KEY (id)
);

CREATE TABLE tb_endereco
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rua    VARCHAR(255),
    bairro VARCHAR(255),
    numero INTEGER,
    cidade VARCHAR(255),
    estado VARCHAR(255),
    CONSTRAINT pk_tb_endereco PRIMARY KEY (id)
);

CREATE TABLE tb_produto
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome       VARCHAR(255),
    descricao  VARCHAR(255),
    preco      DECIMAL,
    local      VARCHAR(255),
    horario    time WITHOUT TIME ZONE,
    usuario_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_produto PRIMARY KEY (id)
);

CREATE TABLE tb_rede_social
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    whatsapp  VARCHAR(255),
    facebook  VARCHAR(255),
    site      VARCHAR(255),
    instagram VARCHAR(255),
    CONSTRAINT pk_tb_rede_social PRIMARY KEY (id)
);

CREATE TABLE tb_tag
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(255),
    CONSTRAINT pk_tb_tag PRIMARY KEY (id)
);

CREATE TABLE tb_usuario
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome           VARCHAR(255),
    sobrenome      VARCHAR(255),
    telefone       VARCHAR(255),
    email          VARCHAR(255),
    password       VARCHAR(255),
    endereco_id    BIGINT,
    role           SMALLINT,
    foto_perfil_id BIGINT,
    rede_social_id BIGINT,
    CONSTRAINT pk_tb_usuario PRIMARY KEY (id)
);

ALTER TABLE tb_arquivo
    ADD CONSTRAINT uc_tb_arquivo_hash UNIQUE (hash);

ALTER TABLE tb_usuario
    ADD CONSTRAINT uc_tb_usuario_email UNIQUE (email);

ALTER TABLE tb_usuario
    ADD CONSTRAINT uc_tb_usuario_endereco UNIQUE (endereco_id);

ALTER TABLE tb_usuario
    ADD CONSTRAINT uc_tb_usuario_foto_perfil UNIQUE (foto_perfil_id);

ALTER TABLE tb_usuario
    ADD CONSTRAINT uc_tb_usuario_rede_social UNIQUE (rede_social_id);

ALTER TABLE tb_arquivo
    ADD CONSTRAINT FK_TB_ARQUIVO_ON_PRODUTO FOREIGN KEY (produto_id) REFERENCES tb_produto (id);

ALTER TABLE tb_produto
    ADD CONSTRAINT FK_TB_PRODUTO_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES tb_usuario (id);

ALTER TABLE tb_usuario
    ADD CONSTRAINT FK_TB_USUARIO_ON_ENDERECO FOREIGN KEY (endereco_id) REFERENCES tb_endereco (id);

ALTER TABLE tb_usuario
    ADD CONSTRAINT FK_TB_USUARIO_ON_FOTO_PERFIL FOREIGN KEY (foto_perfil_id) REFERENCES tb_arquivo (id);

ALTER TABLE tb_usuario
    ADD CONSTRAINT FK_TB_USUARIO_ON_REDE_SOCIAL FOREIGN KEY (rede_social_id) REFERENCES tb_rede_social (id);

ALTER TABLE produto_tag
    ADD CONSTRAINT fk_protag_on_produto FOREIGN KEY (produto_id) REFERENCES tb_produto (id);

ALTER TABLE produto_tag
    ADD CONSTRAINT fk_protag_on_tag FOREIGN KEY (tag_id) REFERENCES tb_tag (id);